# Generated by Django 4.2.4 on 2023-10-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emission",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date_created", models.DateTimeField(verbose_name="Date Created")),
                (
                    "accounting_period",
                    models.CharField(max_length=255, verbose_name="Accounting period"),
                ),
                ("scope_1", models.IntegerField(null=True, verbose_name="Scope 1")),
                ("scope_2", models.IntegerField(null=True, verbose_name="Scope 2")),
                ("scope_3", models.IntegerField(null=True, verbose_name="Scope 3")),
            ],
        ),
    ]
